name: auto_moto_dash
description: Motorcycle/car dashboard Flutter package with HUD, analog gauges, and weather backgrounds.
version: 0.1.0
homepage:

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/weather_bg/
